/**
 * Canonical multipart geometry contract used by both the editor and the map.
 *
 * JSON values deliberately use [x, y, z], while runtime coordinates use
 * objects.  The explicit conversion here prevents old, flattened geometry
 * readers from accidentally treating a second component as another vertex.
 */

export const MULTIPART_GEOMETRY_SCHEMA = 'openriamap.multipart-geometry.v1';
export const DEFAULT_GEOMETRY_Y = -64;

export type MultipartGeometryKind = 'Point' | 'LineString' | 'Polygon';
export type MultipartCoord = { x: number; y: number; z: number };
export type MultipartPointGeometry = { type: 'Point'; parts: MultipartCoord[] };
export type MultipartLineGeometry = { type: 'LineString'; parts: MultipartCoord[][] };
export type MultipartPolygonGeometry = { type: 'Polygon'; parts: MultipartCoord[][][] };
export type MultipartGeometry = MultipartPointGeometry | MultipartLineGeometry | MultipartPolygonGeometry;
export type MultipartGeometryRead = {
  geometry: MultipartGeometry | null;
  source: 'canonical' | 'legacy' | 'none';
  error?: string;
};

type JsonObject = Record<string, unknown>;

const isObject = (value: unknown): value is JsonObject =>
  Boolean(value) && typeof value === 'object' && !Array.isArray(value);

const numberOrNull = (value: unknown): number | null => {
  const numberValue = Number(value);
  return Number.isFinite(numberValue) ? numberValue : null;
};

export function canonicalGeometryField(type: MultipartGeometryKind): 'CoordP' | 'CoordL' | 'CoordG' {
  if (type === 'Point') return 'CoordP';
  if (type === 'LineString') return 'CoordL';
  return 'CoordG';
}

export function geometryTypeFromFeatureType(value: unknown): MultipartGeometryKind | null {
  const type = String(value ?? '').trim();
  if (type === 'Points') return 'Point';
  if (type === 'Polyline') return 'LineString';
  if (type === 'Polygon') return 'Polygon';
  return null;
}

export function featureTypeFromGeometryType(type: MultipartGeometryKind): 'Points' | 'Polyline' | 'Polygon' {
  return type === 'Point' ? 'Points' : type === 'LineString' ? 'Polyline' : 'Polygon';
}

function tupleToCoord(value: unknown): MultipartCoord | null {
  if (!Array.isArray(value) || value.length !== 3) return null;
  const x = numberOrNull(value[0]);
  const y = numberOrNull(value[1]);
  const z = numberOrNull(value[2]);
  return x === null || y === null || z === null ? null : { x, y, z };
}

function legacyTupleToCoord(value: unknown): MultipartCoord | null {
  if (Array.isArray(value)) {
    const x = numberOrNull(value[0]);
    const y = value.length >= 3 ? numberOrNull(value[1]) : DEFAULT_GEOMETRY_Y;
    const z = value.length >= 3 ? numberOrNull(value[2]) : numberOrNull(value[1]);
    return x === null || y === null || z === null ? null : { x, y, z };
  }
  if (!isObject(value)) return null;
  const x = numberOrNull(value.x);
  const z = numberOrNull(value.z);
  const y = numberOrNull(value.y);
  return x === null || z === null ? null : { x, y: y ?? DEFAULT_GEOMETRY_Y, z };
}

function coordinatesEqual(a: MultipartCoord, b: MultipartCoord): boolean {
  return a.x === b.x && a.y === b.y && a.z === b.z;
}

function removeClosingCoordinate(ring: MultipartCoord[]): MultipartCoord[] {
  if (ring.length >= 2 && coordinatesEqual(ring[0], ring[ring.length - 1])) return ring.slice(0, -1);
  return ring;
}

function parseCanonical(value: unknown, type: MultipartGeometryKind): MultipartGeometry | null {
  if (!Array.isArray(value)) return null;
  if (type === 'Point') {
    const parts = value.map(tupleToCoord);
    return parts.every(Boolean) ? { type, parts: parts as MultipartCoord[] } : null;
  }
  if (type === 'LineString') {
    const parts = value.map((part) => Array.isArray(part) ? part.map(tupleToCoord) : null);
    return parts.every((part) => Array.isArray(part) && part.every(Boolean))
      ? { type, parts: parts as MultipartCoord[][] }
      : null;
  }
  const parts = value.map((part) => Array.isArray(part)
    ? part.map((ring) => Array.isArray(ring) ? removeClosingCoordinate(ring.map(tupleToCoord).filter((coord): coord is MultipartCoord => Boolean(coord))) : null)
    : null);
  if (!parts.every((part) => Array.isArray(part) && part.length > 0 && part.every((ring) => Array.isArray(ring)))) return null;
  // Preserve an invalid tuple as an invalid canonical value rather than silently
  // accepting a shortened ring generated by filter above.
  for (const component of value) {
    if (!Array.isArray(component)) return null;
    for (const ring of component) {
      if (!Array.isArray(ring) || ring.some((tuple) => !tupleToCoord(tuple))) return null;
    }
  }
  return { type, parts: parts as MultipartCoord[][][] };
}

function parseLegacy(value: unknown, type: MultipartGeometryKind): MultipartGeometry | null {
  if (type === 'Point') {
    const coord = legacyTupleToCoord(value);
    return coord ? { type, parts: [coord] } : null;
  }
  if (!Array.isArray(value)) return null;
  const path = value.map(legacyTupleToCoord);
  if (!path.every(Boolean)) return null;
  if (type === 'LineString') return { type, parts: [path as MultipartCoord[]] };
  return { type, parts: [[removeClosingCoordinate(path as MultipartCoord[])]] };
}

function stableGeometry(geometry: MultipartGeometry): string {
  return JSON.stringify(serializeMultipartGeometry(geometry));
}

/**
 * Resolve canonical data first. If both canonical and legacy data are present
 * they must describe precisely the same geometry; otherwise callers get a
 * deterministic error instead of rendering stale data.
 */
export function readMultipartGeometry(
  featureInfo: unknown,
  type: MultipartGeometryKind,
  legacySourceField?: string,
): MultipartGeometryRead {
  const info = isObject(featureInfo) ? featureInfo : {};
  const canonicalField = canonicalGeometryField(type);
  const hasCanonical = Object.prototype.hasOwnProperty.call(info, canonicalField);
  const canonical = hasCanonical ? parseCanonical(info[canonicalField], type) : null;
  if (hasCanonical && !canonical) return { geometry: null, source: 'canonical', error: `${canonicalField} 格式无效` };

  const legacyCandidates = Array.from(new Set([
    legacySourceField,
    type === 'Point' ? 'coordinate' : undefined,
    type === 'LineString' ? 'PLpoints' : undefined,
    type === 'LineString' ? 'Linepoints' : undefined,
    type === 'Polygon' ? 'Conpoints' : undefined,
    type === 'Polygon' ? 'Flrpoints' : undefined,
  ].filter((field): field is string => Boolean(field))));
  const legacyEntries = legacyCandidates.filter((field) => Object.prototype.hasOwnProperty.call(info, field));
  const parsedLegacy = legacyEntries.map((field) => ({ field, geometry: parseLegacy(info[field], type) }));
  const invalidLegacy = parsedLegacy.find((entry) => !entry.geometry);
  if (invalidLegacy) return { geometry: null, source: 'legacy', error: `${invalidLegacy.field} 格式无效` };
  const legacy = parsedLegacy[0]?.geometry ?? null;
  if (legacy && parsedLegacy.some((entry) => stableGeometry(entry.geometry as MultipartGeometry) !== stableGeometry(legacy))) {
    return { geometry: null, source: 'legacy', error: 'geometry-field-conflict' };
  }
  if (canonical && legacy && stableGeometry(canonical) !== stableGeometry(legacy)) {
    return { geometry: null, source: 'canonical', error: 'geometry-field-conflict' };
  }
  if (canonical) return { geometry: canonical, source: 'canonical' };
  if (legacy) return { geometry: legacy, source: 'legacy' };
  return { geometry: null, source: 'none' };
}

export function serializeMultipartGeometry(geometry: MultipartGeometry): unknown {
  const tuple = (coord: MultipartCoord): [number, number, number] => [coord.x, coord.y, coord.z];
  if (geometry.type === 'Point') return geometry.parts.map(tuple);
  if (geometry.type === 'LineString') return geometry.parts.map((part) => part.map(tuple));
  return geometry.parts.map((part) => part.map((ring) => removeClosingCoordinate(ring).map(tuple)));
}

export function withCanonicalMultipartGeometry(
  featureInfo: Record<string, unknown>,
  geometry: MultipartGeometry,
): Record<string, unknown> {
  const out = { ...featureInfo };
  out[canonicalGeometryField(geometry.type)] = serializeMultipartGeometry(geometry);
  const legacyFields = geometry.type === 'Point'
    ? ['coordinate']
    : geometry.type === 'LineString'
      ? ['PLpoints', 'Linepoints']
      : ['Conpoints', 'Flrpoints'];
  for (const field of legacyFields) delete out[field];
  return out;
}

/** Create the canonical one-component form used by pre-multipart callers. */
export function multipartGeometryFromSinglePath(
  type: MultipartGeometryKind,
  coords: Array<{ x: number; z: number; y?: number }>,
): MultipartGeometry {
  const normalized = coords.map((coord) => ({
    x: Number(coord.x),
    y: Number.isFinite(Number(coord.y)) ? Number(coord.y) : DEFAULT_GEOMETRY_Y,
    z: Number(coord.z),
  }));
  if (type === 'Point') return { type, parts: normalized };
  if (type === 'LineString') return { type, parts: [normalized] };
  return { type, parts: [[normalized]] };
}

export function firstMultipartCoordinate(geometry: MultipartGeometry | null): MultipartCoord | null {
  if (!geometry) return null;
  if (geometry.type === 'Point') return geometry.parts[0] ?? null;
  if (geometry.type === 'LineString') return geometry.parts[0]?.[0] ?? null;
  return geometry.parts[0]?.[0]?.[0] ?? null;
}

export function flattenMultipartCoordinates(geometry: MultipartGeometry | null): MultipartCoord[] {
  if (!geometry) return [];
  if (geometry.type === 'Point') return geometry.parts;
  if (geometry.type === 'LineString') return geometry.parts.flat();
  return geometry.parts.flat(2);
}

function signedArea(ring: MultipartCoord[]): number {
  let area = 0;
  for (let index = 0; index < ring.length; index += 1) {
    const a = ring[index];
    const b = ring[(index + 1) % ring.length];
    area += a.x * b.z - b.x * a.z;
  }
  return area / 2;
}

function orientation(a: MultipartCoord, b: MultipartCoord, c: MultipartCoord): number {
  const result = (b.x - a.x) * (c.z - a.z) - (b.z - a.z) * (c.x - a.x);
  return Math.abs(result) < 1e-9 ? 0 : result > 0 ? 1 : -1;
}

function onSegment(a: MultipartCoord, b: MultipartCoord, c: MultipartCoord): boolean {
  return Math.min(a.x, c.x) <= b.x && b.x <= Math.max(a.x, c.x)
    && Math.min(a.z, c.z) <= b.z && b.z <= Math.max(a.z, c.z);
}

function segmentsIntersect(a: MultipartCoord, b: MultipartCoord, c: MultipartCoord, d: MultipartCoord): boolean {
  const o1 = orientation(a, b, c);
  const o2 = orientation(a, b, d);
  const o3 = orientation(c, d, a);
  const o4 = orientation(c, d, b);
  if (o1 !== o2 && o3 !== o4) return true;
  return (o1 === 0 && onSegment(a, c, b)) || (o2 === 0 && onSegment(a, d, b))
    || (o3 === 0 && onSegment(c, a, d)) || (o4 === 0 && onSegment(c, b, d));
}

function ringSelfIntersects(ring: MultipartCoord[]): boolean {
  for (let i = 0; i < ring.length; i += 1) {
    const a = ring[i];
    const b = ring[(i + 1) % ring.length];
    for (let j = i + 1; j < ring.length; j += 1) {
      if (j === i || (j + 1) % ring.length === i || (i + 1) % ring.length === j) continue;
      const c = ring[j];
      const d = ring[(j + 1) % ring.length];
      if (segmentsIntersect(a, b, c, d)) return true;
    }
  }
  return false;
}

function pointInRing(point: MultipartCoord, ring: MultipartCoord[]): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const a = ring[i];
    const b = ring[j];
    const intersects = ((a.z > point.z) !== (b.z > point.z))
      && point.x < ((b.x - a.x) * (point.z - a.z)) / (b.z - a.z) + a.x;
    if (intersects) inside = !inside;
  }
  return inside;
}

function ringsIntersect(a: MultipartCoord[], b: MultipartCoord[]): boolean {
  for (let ai = 0; ai < a.length; ai += 1) {
    const aNext = a[(ai + 1) % a.length];
    for (let bi = 0; bi < b.length; bi += 1) {
      if (segmentsIntersect(a[ai], aNext, b[bi], b[(bi + 1) % b.length])) return true;
    }
  }
  return false;
}

/**
 * Validate a polygon-hole draft before it is committed to the multipart
 * editor.  Unlike validateMultipartGeometry this accepts an incomplete ring:
 * it is intended for map clicks, control-point moves, manual input and array
 * previews, where rejecting an impossible point immediately is preferable to
 * letting an invalid draft survive until Save.
 */
export function validateMultipartHoleDraft(
  geometry: MultipartGeometry | null,
  partIndex: number,
  holeIndex: number,
  candidate: MultipartCoord[],
): string | undefined {
  if (!geometry || geometry.type !== 'Polygon') return undefined;
  const component = geometry.parts[partIndex];
  const outer = component?.[0];
  if (!outer || outer.length < 3) return '内部洞必须先在有效的外边界内编辑';

  const holeLabel = `第 ${partIndex + 1} 个部件内部洞 ${holeIndex + 1}`;
  if (candidate.some((point) => !pointInRing(point, outer))) {
    return `${holeLabel} 的控制点必须位于外边界内`;
  }

  // Every completed draft segment must stay inside the exterior.  Test only
  // consecutive segments while the ring is incomplete; the closing segment is
  // checked by validateMultipartGeometry when the user saves the geometry.
  for (let index = 1; index < candidate.length; index += 1) {
    const a = candidate[index - 1];
    const b = candidate[index];
    for (let outerIndex = 0; outerIndex < outer.length; outerIndex += 1) {
      const c = outer[outerIndex];
      const d = outer[(outerIndex + 1) % outer.length];
      if (segmentsIntersect(a, b, c, d)) return `${holeLabel} 不能穿越外边界`;
    }
  }

  const otherHoles = component.slice(1);
  for (let index = 0; index < otherHoles.length; index += 1) {
    if (index === holeIndex) continue;
    const other = otherHoles[index];
    if (!other?.length) continue;
    if (candidate.some((point) => pointInRing(point, other))) {
      return `${holeLabel} 不能进入其他内部洞`;
    }
    for (let segment = 1; segment < candidate.length; segment += 1) {
      for (let otherIndex = 0; otherIndex < other.length; otherIndex += 1) {
        if (segmentsIntersect(candidate[segment - 1], candidate[segment], other[otherIndex], other[(otherIndex + 1) % other.length])) {
          return `${holeLabel} 不能与其他内部洞相交`;
        }
      }
    }
  }

  return undefined;
}

export function validateMultipartGeometry(geometry: MultipartGeometry | null): string | undefined {
  if (!geometry) return '缺少几何坐标';
  const invalidCoordinate = flattenMultipartCoordinates(geometry).find((coord) =>
    !Number.isFinite(coord.x) || !Number.isFinite(coord.y) || !Number.isFinite(coord.z));
  if (invalidCoordinate) return '坐标必须为有限的 [x, y, z] 数字';
  if (geometry.type === 'Point') return geometry.parts.length > 0 ? undefined : 'CoordP 至少需要 1 个坐标';
  if (geometry.type === 'LineString') {
    const invalidPart = geometry.parts.findIndex((part) => part.length < 2);
    return invalidPart >= 0 ? `CoordL 第 ${invalidPart + 1} 个部件至少需要 2 个坐标` : undefined;
  }
  for (let partIndex = 0; partIndex < geometry.parts.length; partIndex += 1) {
    const [outer, ...holes] = geometry.parts[partIndex];
    if (!outer || outer.length < 3) return `CoordG 第 ${partIndex + 1} 个部件外边界至少需要 3 个坐标`;
    if (Math.abs(signedArea(outer)) < 1e-9 || ringSelfIntersects(outer)) return `CoordG 第 ${partIndex + 1} 个部件外边界拓扑无效`;
    for (let holeIndex = 0; holeIndex < holes.length; holeIndex += 1) {
      const hole = holes[holeIndex];
      if (hole.length < 3 || Math.abs(signedArea(hole)) < 1e-9 || ringSelfIntersects(hole)) return `CoordG 第 ${partIndex + 1} 个部件内部洞 ${holeIndex + 1} 拓扑无效`;
      if (!pointInRing(hole[0], outer) || ringsIntersect(hole, outer)) return `CoordG 第 ${partIndex + 1} 个部件内部洞 ${holeIndex + 1} 必须完全位于外边界内`;
      for (let prior = 0; prior < holeIndex; prior += 1) {
        if (ringsIntersect(hole, holes[prior]) || pointInRing(hole[0], holes[prior])) return `CoordG 第 ${partIndex + 1} 个部件内部洞不能重叠`;
      }
    }
  }
  return undefined;
}
